FROM apache/airflow:2.7.0-python3.8
LABEL authors="alchemine <djyoon0223@gmail.com>"

# --------------------------------------------------
# 1. Copy configuration
# --------------------------------------------------
COPY airflow.cfg ${AIRFLOW_HOME}/


# --------------------------------------------------
# 2. Install apt packages
# --------------------------------------------------
USER root
RUN apt-get update && \
    apt-get install -yqq --no-install-recommends \
    procps \
    openssh-server \
    vim \
    net-tools && \
    apt-get autoremove -yqq --purge && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
USER airflow


# --------------------------------------------------
# 3. Install PyPI packages
# --------------------------------------------------
COPY requirements.txt /
RUN pip install --no-cache-dir "apache-airflow==${AIRFLOW_VERSION}" -r /requirements.txt
