FROM bde2020/hive:2.3.2-postgresql-metastore AS jdk
FROM apache/airflow:2.7.0-python3.8
LABEL authors="alchemine <djyoon0223@gmail.com>"


# --------------------------------------------------
# 1. Copy configuration
# --------------------------------------------------
COPY airflow.cfg ${AIRFLOW_HOME}/


USER root

# --------------------------------------------------
# 2. Install apt packages
# --------------------------------------------------
RUN apt-get update && \
    apt-get install -yqq --no-install-recommends \
    procps \
    openssh-server \
    vim \
    software-properties-common \
    net-tools && \
    apt-get autoremove -yqq --purge && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# --------------------------------------------------
# 3. Install Java
# --------------------------------------------------
COPY --from=jdk /usr/lib/jvm/java-8-openjdk-amd64 /usr/lib/jvm/java-8-openjdk-amd64
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

USER airflow


# --------------------------------------------------
# 4. Install PyPI packages
# --------------------------------------------------
COPY requirements.txt /
RUN pip install --no-cache-dir "apache-airflow==${AIRFLOW_VERSION}" -r /requirements.txt
